#!/usr/bin/env bash
# displays information about subdomains

sub_domain_info () {
    code=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $code" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}
if [ "$#" == 1 ]
then
    sub_domain_info "$1" "www"
    sub_domain_info "$1" "lb-01"
    sub_domain_info "$1" "web-01"
    sub_domain_info "$1" "web-02"
elif [ "$#" == 2 ]
then
    sub_domain_info "$1" "$2"
fi
