#!/usr/bin/env bash
# Bash script to install nginx server
apt-get update && apt-get upgrade -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
