#!/usr/bin/env bash
# Script to configure a new Ubuntu machine with respect to above the requirements

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
replacement_str="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Sampul-CodeMine permanent;"
sudo sed -i "s/server_name _;/$replacement_str/" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
