#!/usr/bin/env bash
# Script to configure a new Ubuntu machine with respect to above the requirements

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
stringreplace="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com/@sampulcodemine/playlists permanent;"
sudo sed -i "s/server_name _;/$stringreplace/" /etc/nginx/sites-enabled/default

sudo service nginx restart
