#!/usr/bin/env bash
# Bash script to configure Nginx so that its 
#HTTP response contains a custom header: web-01 and web-02

#update the app repository for Ubuntu
sudo apt-get update && sudo apt-get upgrade -y

#install NGINX
sudo apt-get install nginx -y

#Allow NGINX to run from PORT 80 
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 22

#Setting the Home page for Nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

#Creating a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

echo "
server  {
        listen 80 default_server;
        listen [::]:80 default_server;
        root   /var/www/html;
        index  index.html index.htm;
        add_header X-Served-By $HOSTNAME;
        location /redirect_me {
            return 301 https://github.com/Sampul-CodeMine;
        }
        error_page 404 /404.html;
        location /404.html {
            root /var/www/html;
            internal;
        }
        location / {
            # First attempt to serve request as file, then
            # as directory, then fall back to displaying a 404.
            try_files $uri $uri/ =404;
        }

}
" | sudo tee /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
