#!/usr/bin/env bash
# Bash script to configure Nginx so that its 
#HTTP response contains a custom header: web-01 and web-02
sudo apt update && sudo apt upgrade -y
sudo apt install nginx -y

sudo ufw allow 'Nginx HTTP'
sudo ufw allow 22

sudo mkdir -p /var/www/html

sudo chmod -R 755 /var/www

# creating the index.html page and 404 error page
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

string_one="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"
sudo sed -i "s/server_name _;/$string_one/" /etc/nginx/sites-enabled/default

string_two="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_two/" /etc/nginx/sites-enabled/default

sudo service nginx restart
