#!/busr/bin/env bash
#This is a Bash Script that installs and configure HAProxy on lb-01 Load Balancer server
#to send traffic to wev-server web-01 and web-server web-02 using the RoundRobin algorithm

sudo apt update && sudo apt upgrade -y

#editing the configuration file
server_config=\
"
frontend webapp-frontend
	bind *:80
	mode http
	default_backend webapp-backend
backend webapp-backend
	balance roundrobin
	server 217820-web-01 3.84.237.114:80 check
	server 217820-web-02 100.25.131.115:80 check
"

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
