#!/usr/bin/env bash
#This is a Bash Script that installs and configure HAProxy on lb-01 Load Balancer server
#to send traffic to wev-server web-01 and web-server web-02 using the RoundRobin algorithm

sudo apt update && sudo apt upgrade -y

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get install -y haproxy=2.7.\*

#editing the configuration file
 server_config=\
"
frontend alxapp-frontend
        bind *:80
        mode http
        default_backend alxapp-backend
backend alxapp-backend
        balance roundrobin
        server 217820-web-01 100.26.10.14:80 check
        server 217820-web-02 100.25.129.135:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
