#!/usr/bin/env bash
#This is a Bash Script that installs and configure HAProxy on lb-01 Load Balancer server
#to send traffic to wev-server web-01 and web-server web-02 using the RoundRobin algorithm

sudo apt update && sudo apt upgrade -y

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get install haproxy=2.7.\*

#editing the configuration file
 server_config=\
  9 "
 10 frontend webapp-frontend
 11         bind *:80
 12         mode http
 13         default_backend webapp-backend
 14 backend webapp-backend
 15         balance roundrobin
 16         server 217820-web-01 3.84.237.114:80 check
 17         server 217820-web-02 100.25.131.115:80 check
 18 "
 19
 20 echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
 21
 22 echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
 23
 24 sudo service haproxy restart
