#!usr/bin/env bash

sudo apt-key add mysql_repo.key
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-cache policy mysql-server
sudo apt install -f mysql-client=5.7* mysql-community-server=5.7* mysql-server=5.7*
