#!/usr/bin/env bash
# Shell script that pings an IP addr passed as an argument else displays an error if the argument is empty.

if [ "$1" == "" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
