#!/usr/bin/env bash
# Shell Script to display the contents of the file `/etc/passwd`.
# gets the username, user id, and user home directory path.

myfile="/etc/passwd"
while IFS= read -r line
do
	echo "$line" | cut -d":" -f1,3,6
done < "$myfile"
