#!/usr/bin/env bash
# Shell script to displays string 10 times and hi after
# the 9th using WHILE and IF

i=1

while [ $i -le 10 ]
do
	echo "Best School"
    	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	((i++))
done
