#!/usr/bin/env bash
# Shell script that displays the contents of the current directory
# In a list format
# Ignoring the first dash of the filename

mylist=$(ls)

for i in $mylist; do
	echo "$i" | cut -d '-' -f2
done
